### ISSUE TITLE
没有搜索到该库

### ISSUE THREAD

**Issue by quanqiuheike** [senonwx/ModularizationApp#2]
Unable to resolve dependency for ':lib_common@debug/compileClasspath': Could not resolve me.jessyan:autosize:1.0.6.

**Comment by senonwx** [comment]
android studio版本是否为3.0以上。出现此问题可能是因为android studio在离线时无法下载资源，解决办法打开File->Settings->Build, Execution, Deployment->Gradle->取消选中 Offline work 按钮
