### ISSUE TITLE
想向您请教一下关于模块划分的问题

### ISSUE THREAD

**Issue by MarkFrank01** [senonwx/ModularizationApp#3]
日常开发中该如何对模块进行划分呢，之前尝试过模块化，但是感觉自己水平不足，仍不能很好的进行划分，老哥能否指点一下~~~

**Comment by senonwx** [comment]
模块划分主要还是为了解耦和复用，没有最好的模块划分，需要针对不同业务来划分不同的模块，一般来说分为以下几个不同模块：
主模块
做为所有业务模块的壳，初始化各个组件等。
业务模块
建议早期实施模块化的时候,可以以一种”较粗”的粒度来进行，这样左右的好处在于后期随着对业务的理解进行再次细分，而不会有太大的成本，这也是一个孰能生巧的过程。
common模块
存放一些要使用到的三方库，最好封装好，比如支付、分享、登录等业务这一块都可以放在这里
base模块
这里主要存放一些base类，封装好的baseactivity、basefragment等，网络模块、数据库操作等也可放这里，当然也可以放common子模块
希望能对你有帮助
