### ISSUE TITLE
Model层不进行封装么？

### ISSUE THREAD

**Issue by BroganGrow** [senonwx/ModularizationApp#5]
网上好少关于model的封装

**Comment by senonwx** [comment]
ServerUtils已经封装的比较好了，满足大部分网络请求功能，如果数据库读取或者业务比较频繁可以使用。
m层封装[`ModelRequestMod.java`](https://github.com/senonwx/ModularApp/blob/master/lib_common/src/main/java/com/senon/lib_common/common/model/ModelRequestMod.java)
